### ISSUE TITLE
Add dependencies from Plone package

### ISSUE THREAD

**Issue by ericof** [plone/plone.classicui#12]
As it should be possible to install `plone.classicui` instead of `Plone`, we have to make sure all packages listed there are also listed here.

**Comment by mauritsvanrees** [comment]
I am not sure about this.  This is not how I imagined `plone.classicui` until now.  Could be okay though.

In the PR you currently add these, in addition to `plone.distribution`:

```
        "Products.CMFPlacefulWorkflow",
        "plone.app.caching",
        "plone.app.discussion",
        "plone.app.iterate",
        "plone.app.multilingual",
        "Products.CMFPlone",
```

Compared with the `Plone` egg, this misses:

* `plone.volto`, for obvious reasons
* `plone.restapi`, but that gets pulled in by `plone.distribution`
* `plone.app.upgrade`

I am inclined to only have `Products.CMFPlone` here.  Not everyone needs Iterate or CMFPlacefulWorkflow.  In 6.1 we have made Multilingual a core add-on on top of CMFPlone, and same is almost finished for Discussion.

Some thoughts:

1. To me this new dependency list signals that `plone.classicui` (and `plone.volto` where I see you are doing the same) are example distributions.  They are fine to test Plone.  They are fine as a basis for your own project if you are not so experienced with Plone.
2. But if you know what you are doing, you are expected to make your own distributions.  That can be one distribution for each project you do, or one base distribution that you use for all/most sites in your organisation.  Then you can pick your own favourite (core) add-ons and have your own sample contents.
3. You cannot re-use the sample contents of `plone.classicui`, unless you are fine with its choice of add-ons.

I guess this is a fine approach as well, just a bit different than I had expected or was planning for.

But then I would say: add `plone.app.upgrade` to the install requirements of both `plone.classicui` and `plone.volto`.  This is best for our target audience of inexperienced users.  Otherwise the first time they do a bugfix update, they won't be able to run the `@@plone-upgrade` steps.

cc @plone/classicui-team

**Comment by jensens** [comment]
No, that is not the idea to add those here. See my post https://community.plone.org/t/plone-6-1-architecture-and-mental-model/
